// Copyright 2022 Manna Harbour
// https://github.com/manna-harbour/miryoku

#if !defined (MIRYOKU_LAYOUTMAPPING_CORNE2)

#define XXX &none

/*
 * Extra key positions:
 *
 * Row 0:
 *   E00 K00 K01 K02 K03 K04    E01    K05 K06 K07 K08 K09 E02
 *
 * Row 1:
 *   E03 K10 K11 K12 K13 K14    E04 E05 E06    K15 K16 K17 K18 K19 E07
 *
 * Row 2:
 *   E08 K20 K21 K22 K23 K24 E09    E10    K25 K26 K27 K28 K29 E11
 *
 * Row 3:
 *                         K32 K33 K34    K35 K36 K37
 */

/* ---------- default extra keys: Base ---------- */
#ifndef EYELASH_E00_BASE
#define EYELASH_E00_BASE XXX
#endif
#ifndef EYELASH_E01_BASE
#define EYELASH_E01_BASE XXX
#endif
#ifndef EYELASH_E02_BASE
#define EYELASH_E02_BASE XXX
#endif
#ifndef EYELASH_E03_BASE
#define EYELASH_E03_BASE XXX
#endif
#ifndef EYELASH_E04_BASE
#define EYELASH_E04_BASE XXX
#endif
#ifndef EYELASH_E05_BASE
#define EYELASH_E05_BASE XXX
#endif
#ifndef EYELASH_E06_BASE
#define EYELASH_E06_BASE XXX
#endif
#ifndef EYELASH_E07_BASE
#define EYELASH_E07_BASE XXX
#endif
#ifndef EYELASH_E08_BASE
#define EYELASH_E08_BASE XXX
#endif
#ifndef EYELASH_E09_BASE
#define EYELASH_E09_BASE XXX
#endif
#ifndef EYELASH_E10_BASE
#define EYELASH_E10_BASE XXX
#endif
#ifndef EYELASH_E11_BASE
#define EYELASH_E11_BASE XXX
#endif

/* ---------- Extra layer ---------- */
#ifndef EYELASH_E00_EXTRA
#define EYELASH_E00_EXTRA XXX
#endif
#ifndef EYELASH_E01_EXTRA
#define EYELASH_E01_EXTRA XXX
#endif
#ifndef EYELASH_E02_EXTRA
#define EYELASH_E02_EXTRA XXX
#endif
#ifndef EYELASH_E03_EXTRA
#define EYELASH_E03_EXTRA XXX
#endif
#ifndef EYELASH_E04_EXTRA
#define EYELASH_E04_EXTRA XXX
#endif
#ifndef EYELASH_E05_EXTRA
#define EYELASH_E05_EXTRA XXX
#endif
#ifndef EYELASH_E06_EXTRA
#define EYELASH_E06_EXTRA XXX
#endif
#ifndef EYELASH_E07_EXTRA
#define EYELASH_E07_EXTRA XXX
#endif
#ifndef EYELASH_E08_EXTRA
#define EYELASH_E08_EXTRA XXX
#endif
#ifndef EYELASH_E09_EXTRA
#define EYELASH_E09_EXTRA XXX
#endif
#ifndef EYELASH_E10_EXTRA
#define EYELASH_E10_EXTRA XXX
#endif
#ifndef EYELASH_E11_EXTRA
#define EYELASH_E11_EXTRA XXX
#endif

/* ---------- Tap layer ---------- */
#ifndef EYELASH_E00_TAP
#define EYELASH_E00_TAP XXX
#endif
#ifndef EYELASH_E01_TAP
#define EYELASH_E01_TAP XXX
#endif
#ifndef EYELASH_E02_TAP
#define EYELASH_E02_TAP XXX
#endif
#ifndef EYELASH_E03_TAP
#define EYELASH_E03_TAP XXX
#endif
#ifndef EYELASH_E04_TAP
#define EYELASH_E04_TAP XXX
#endif
#ifndef EYELASH_E05_TAP
#define EYELASH_E05_TAP XXX
#endif
#ifndef EYELASH_E06_TAP
#define EYELASH_E06_TAP XXX
#endif
#ifndef EYELASH_E07_TAP
#define EYELASH_E07_TAP XXX
#endif
#ifndef EYELASH_E08_TAP
#define EYELASH_E08_TAP XXX
#endif
#ifndef EYELASH_E09_TAP
#define EYELASH_E09_TAP XXX
#endif
#ifndef EYELASH_E10_TAP
#define EYELASH_E10_TAP XXX
#endif
#ifndef EYELASH_E11_TAP
#define EYELASH_E11_TAP XXX
#endif

/* ---------- Button layer ---------- */
#ifndef EYELASH_E00_BUTTON
#define EYELASH_E00_BUTTON XXX
#endif
#ifndef EYELASH_E01_BUTTON
#define EYELASH_E01_BUTTON XXX
#endif
#ifndef EYELASH_E02_BUTTON
#define EYELASH_E02_BUTTON XXX
#endif
#ifndef EYELASH_E03_BUTTON
#define EYELASH_E03_BUTTON XXX
#endif
#ifndef EYELASH_E04_BUTTON
#define EYELASH_E04_BUTTON XXX
#endif
#ifndef EYELASH_E05_BUTTON
#define EYELASH_E05_BUTTON XXX
#endif
#ifndef EYELASH_E06_BUTTON
#define EYELASH_E06_BUTTON XXX
#endif
#ifndef EYELASH_E07_BUTTON
#define EYELASH_E07_BUTTON XXX
#endif
#ifndef EYELASH_E08_BUTTON
#define EYELASH_E08_BUTTON XXX
#endif
#ifndef EYELASH_E09_BUTTON
#define EYELASH_E09_BUTTON XXX
#endif
#ifndef EYELASH_E10_BUTTON
#define EYELASH_E10_BUTTON XXX
#endif
#ifndef EYELASH_E11_BUTTON
#define EYELASH_E11_BUTTON XXX
#endif

/* ---------- Nav layer ---------- */
#ifndef EYELASH_E00_NAV
#define EYELASH_E00_NAV XXX
#endif
#ifndef EYELASH_E01_NAV
#define EYELASH_E01_NAV XXX
#endif
#ifndef EYELASH_E02_NAV
#define EYELASH_E02_NAV XXX
#endif
#ifndef EYELASH_E03_NAV
#define EYELASH_E03_NAV XXX
#endif
#ifndef EYELASH_E04_NAV
#define EYELASH_E04_NAV XXX
#endif
#ifndef EYELASH_E05_NAV
#define EYELASH_E05_NAV XXX
#endif
#ifndef EYELASH_E06_NAV
#define EYELASH_E06_NAV XXX
#endif
#ifndef EYELASH_E07_NAV
#define EYELASH_E07_NAV XXX
#endif
#ifndef EYELASH_E08_NAV
#define EYELASH_E08_NAV XXX
#endif
#ifndef EYELASH_E09_NAV
#define EYELASH_E09_NAV XXX
#endif
#ifndef EYELASH_E10_NAV
#define EYELASH_E10_NAV XXX
#endif
#ifndef EYELASH_E11_NAV
#define EYELASH_E11_NAV XXX
#endif

/* ---------- Mouse layer ---------- */
#ifndef EYELASH_E00_MOUSE
#define EYELASH_E00_MOUSE XXX
#endif
#ifndef EYELASH_E01_MOUSE
#define EYELASH_E01_MOUSE XXX
#endif
#ifndef EYELASH_E02_MOUSE
#define EYELASH_E02_MOUSE XXX
#endif
#ifndef EYELASH_E03_MOUSE
#define EYELASH_E03_MOUSE XXX
#endif
#ifndef EYELASH_E04_MOUSE
#define EYELASH_E04_MOUSE XXX
#endif
#ifndef EYELASH_E05_MOUSE
#define EYELASH_E05_MOUSE XXX
#endif
#ifndef EYELASH_E06_MOUSE
#define EYELASH_E06_MOUSE XXX
#endif
#ifndef EYELASH_E07_MOUSE
#define EYELASH_E07_MOUSE XXX
#endif
#ifndef EYELASH_E08_MOUSE
#define EYELASH_E08_MOUSE XXX
#endif
#ifndef EYELASH_E09_MOUSE
#define EYELASH_E09_MOUSE XXX
#endif
#ifndef EYELASH_E10_MOUSE
#define EYELASH_E10_MOUSE XXX
#endif
#ifndef EYELASH_E11_MOUSE
#define EYELASH_E11_MOUSE XXX
#endif

/* ---------- Media layer ---------- */
#ifndef EYELASH_E00_MEDIA
#define EYELASH_E00_MEDIA XXX
#endif
#ifndef EYELASH_E01_MEDIA
#define EYELASH_E01_MEDIA XXX
#endif
#ifndef EYELASH_E02_MEDIA
#define EYELASH_E02_MEDIA XXX
#endif
#ifndef EYELASH_E03_MEDIA
#define EYELASH_E03_MEDIA XXX
#endif
#ifndef EYELASH_E04_MEDIA
#define EYELASH_E04_MEDIA XXX
#endif
#ifndef EYELASH_E05_MEDIA
#define EYELASH_E05_MEDIA XXX
#endif
#ifndef EYELASH_E06_MEDIA
#define EYELASH_E06_MEDIA XXX
#endif
#ifndef EYELASH_E07_MEDIA
#define EYELASH_E07_MEDIA XXX
#endif
#ifndef EYELASH_E08_MEDIA
#define EYELASH_E08_MEDIA XXX
#endif
#ifndef EYELASH_E09_MEDIA
#define EYELASH_E09_MEDIA XXX
#endif
#ifndef EYELASH_E10_MEDIA
#define EYELASH_E10_MEDIA XXX
#endif
#ifndef EYELASH_E11_MEDIA
#define EYELASH_E11_MEDIA XXX
#endif

/* ---------- Num layer ---------- */
#ifndef EYELASH_E00_NUM
#define EYELASH_E00_NUM XXX
#endif
#ifndef EYELASH_E01_NUM
#define EYELASH_E01_NUM XXX
#endif
#ifndef EYELASH_E02_NUM
#define EYELASH_E02_NUM XXX
#endif
#ifndef EYELASH_E03_NUM
#define EYELASH_E03_NUM XXX
#endif
#ifndef EYELASH_E04_NUM
#define EYELASH_E04_NUM XXX
#endif
#ifndef EYELASH_E05_NUM
#define EYELASH_E05_NUM XXX
#endif
#ifndef EYELASH_E06_NUM
#define EYELASH_E06_NUM XXX
#endif
#ifndef EYELASH_E07_NUM
#define EYELASH_E07_NUM XXX
#endif
#ifndef EYELASH_E08_NUM
#define EYELASH_E08_NUM XXX
#endif
#ifndef EYELASH_E09_NUM
#define EYELASH_E09_NUM XXX
#endif
#ifndef EYELASH_E10_NUM
#define EYELASH_E10_NUM XXX
#endif
#ifndef EYELASH_E11_NUM
#define EYELASH_E11_NUM XXX
#endif

/* ---------- Sym layer ---------- */
#ifndef EYELASH_E00_SYM
#define EYELASH_E00_SYM XXX
#endif
#ifndef EYELASH_E01_SYM
#define EYELASH_E01_SYM XXX
#endif
#ifndef EYELASH_E02_SYM
#define EYELASH_E02_SYM XXX
#endif
#ifndef EYELASH_E03_SYM
#define EYELASH_E03_SYM XXX
#endif
#ifndef EYELASH_E04_SYM
#define EYELASH_E04_SYM XXX
#endif
#ifndef EYELASH_E05_SYM
#define EYELASH_E05_SYM XXX
#endif
#ifndef EYELASH_E06_SYM
#define EYELASH_E06_SYM XXX
#endif
#ifndef EYELASH_E07_SYM
#define EYELASH_E07_SYM XXX
#endif
#ifndef EYELASH_E08_SYM
#define EYELASH_E08_SYM XXX
#endif
#ifndef EYELASH_E09_SYM
#define EYELASH_E09_SYM XXX
#endif
#ifndef EYELASH_E10_SYM
#define EYELASH_E10_SYM XXX
#endif
#ifndef EYELASH_E11_SYM
#define EYELASH_E11_SYM XXX
#endif

/* ---------- Fun layer ---------- */
#ifndef EYELASH_E00_FUN
#define EYELASH_E00_FUN XXX
#endif
#ifndef EYELASH_E01_FUN
#define EYELASH_E01_FUN XXX
#endif
#ifndef EYELASH_E02_FUN
#define EYELASH_E02_FUN XXX
#endif
#ifndef EYELASH_E03_FUN
#define EYELASH_E03_FUN XXX
#endif
#ifndef EYELASH_E04_FUN
#define EYELASH_E04_FUN XXX
#endif
#ifndef EYELASH_E05_FUN
#define EYELASH_E05_FUN XXX
#endif
#ifndef EYELASH_E06_FUN
#define EYELASH_E06_FUN XXX
#endif
#ifndef EYELASH_E07_FUN
#define EYELASH_E07_FUN XXX
#endif
#ifndef EYELASH_E08_FUN
#define EYELASH_E08_FUN XXX
#endif
#ifndef EYELASH_E09_FUN
#define EYELASH_E09_FUN XXX
#endif
#ifndef EYELASH_E10_FUN
#define EYELASH_E10_FUN XXX
#endif
#ifndef EYELASH_E11_FUN
#define EYELASH_E11_FUN XXX
#endif

#define MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS( \
K00, K01, K02, K03, K04,           K05, K06, K07, K08, K09, \
K10, K11, K12, K13, K14,           K15, K16, K17, K18, K19, \
K20, K21, K22, K23, K24,           K25, K26, K27, K28, K29, \
N30, N31, K32, K33, K34,           K35, K36, K37, N38, N39, \
E00, E01, E02, E03, E04, E05 \
) \
XXX K00 K01 K02 K03 K04          E00     K05 K06 K07 K08 K09 XXX \
XXX K10 K11 K12 K13 K14      E01 E02 E03 K15 K16 K17 K18 K19 XXX \
XXX K20 K21 K22 K23 K24 E04      E05     K25 K26 K27 K28 K29 XXX \
            K32 K33 K34                  K35 K36 K37

#define MIRYOKU_LAYOUTMAPPING_CORNE2( \
K00, K01, K02, K03, K04,           K05, K06, K07, K08, K09, \
K10, K11, K12, K13, K14,           K15, K16, K17, K18, K19, \
K20, K21, K22, K23, K24,           K25, K26, K27, K28, K29, \
N30, N31, K32, K33, K34,           K35, K36, K37, N38, N39 \
) \
XXX K00 K01 K02 K03 K04          E01     K05 K06 K07 K08 K09 XXX \
XXX K10 K11 K12 K13 K14      E04 E05 E06 K15 K16 K17 K18 K19 XXX \
XXX K20 K21 K22 K23 K24 E09      E10     K25 K26 K27 K28 K29 XXX \
            K32 K33 K34                  K35 K36 K37

#define MIRYOKU_LAYERMAPPING_BASE(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_BASE, EYELASH_E01_BASE, EYELASH_E02_BASE, \
EYELASH_E03_BASE, EYELASH_E04_BASE, EYELASH_E05_BASE)

#define MIRYOKU_LAYERMAPPING_EXTRA(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_EXTRA, EYELASH_E01_EXTRA, EYELASH_E02_EXTRA, \
EYELASH_E03_EXTRA, EYELASH_E04_EXTRA, EYELASH_E05_EXTRA)

#define MIRYOKU_LAYERMAPPING_TAP(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_TAP, EYELASH_E01_TAP, EYELASH_E02_TAP, \
EYELASH_E03_TAP, EYELASH_E04_TAP, EYELASH_E05_TAP)

#define MIRYOKU_LAYERMAPPING_BUTTON(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_BUTTON, EYELASH_E01_BUTTON, EYELASH_E02_BUTTON, \
EYELASH_E03_BUTTON, EYELASH_E04_BUTTON, EYELASH_E05_BUTTON)

#define MIRYOKU_LAYERMAPPING_NAV(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_NAV, EYELASH_E01_NAV, EYELASH_E02_NAV, \
EYELASH_E03_NAV, EYELASH_E04_NAV, EYELASH_E05_NAV)

#define MIRYOKU_LAYERMAPPING_MOUSE(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_MOUSE, EYELASH_E01_MOUSE, EYELASH_E02_MOUSE, \
EYELASH_E03_MOUSE, EYELASH_E04_MOUSE, EYELASH_E05_MOUSE)

#define MIRYOKU_LAYERMAPPING_MEDIA(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_MEDIA, EYELASH_E01_MEDIA, EYELASH_E02_MEDIA, \
EYELASH_E03_MEDIA, EYELASH_E04_MEDIA, EYELASH_E05_MEDIA)

#define MIRYOKU_LAYERMAPPING_NUM(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_NUM, EYELASH_E01_NUM, EYELASH_E02_NUM, \
EYELASH_E03_NUM, EYELASH_E04_NUM, EYELASH_E05_NUM)

#define MIRYOKU_LAYERMAPPING_SYM(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_SYM, EYELASH_E01_SYM, EYELASH_E02_SYM, \
EYELASH_E03_SYM, EYELASH_E04_SYM, EYELASH_E05_SYM)

#define MIRYOKU_LAYERMAPPING_FUN(...) \
MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS(__VA_ARGS__, \
EYELASH_E00_FUN, EYELASH_E01_FUN, EYELASH_E02_FUN, \
EYELASH_E03_FUN, EYELASH_E04_FUN, EYELASH_E05_FUN)

#endif

#define MIRYOKU_MAPPING MIRYOKU_LAYOUTMAPPING_CORNE2_EXTRAS