name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "boards/arm/eyelash_corne/*.keymap"
      - "boards/arm/eyelash_corne/*.dtsi"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "boards/arm/eyelash_corne/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"